Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"
  config.vm.network :forwarded_port, guest: 443, host: 8443

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
 config.vm.provision :shell, path: "vagrant-script/bootstrap.sh"
 config.vm.provision :shell, path: "vagrant-script/start-server.sh", run:"always"
end
