// flow-typed signature: 7938b96911fb63ee94da89bd7d6c772b
// flow-typed version: <<STUB>>/babel-plugin-transform-imports_v1.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-imports/test/invalidTransform' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-imports/test/tests' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-imports/test/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-imports/index' {
  declare module.exports: $Exports<'babel-plugin-transform-imports'>;
}
declare module 'babel-plugin-transform-imports/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports'>;
}
declare module 'babel-plugin-transform-imports/test/invalidTransform.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports/test/invalidTransform'>;
}
declare module 'babel-plugin-transform-imports/test/tests.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports/test/tests'>;
}
declare module 'babel-plugin-transform-imports/test/transform.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports/test/transform'>;
}
