// flow-typed signature: ce4d93b822c78f3cdaf2ab6566b2b333
// flow-typed version: <<STUB>>/object-diff_v0.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object-diff/index' {
  declare module.exports: $Exports<'object-diff'>;
}
declare module 'object-diff/index.js' {
  declare module.exports: $Exports<'object-diff'>;
}
