// flow-typed signature: 7f7665c3393c8c636f68d43b949405f6
// flow-typed version: <<STUB>>/screenfull_v3.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'screenfull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'screenfull' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'screenfull/dist/screenfull' {
  declare module.exports: any;
}

// Filename aliases
declare module 'screenfull/dist/screenfull.js' {
  declare module.exports: $Exports<'screenfull/dist/screenfull'>;
}
